title: Youguang Xing's Homepage
page-top-title: Youguang Xing
top-section-bg-text: Computer Science&ensp;|&ensp;Robotics
home-subtitle: Youguang Xing&ensp;|&ensp;邢佑广
copyright-text: '&copy; Youguang Xing 2025-2026. All Rights Reserved.'
